[build-system]
build-backend = "setuptools.build_meta"

requires = [ "setuptools", "wheel" ]

[project]
name = "template-python"
version = "0.1"
description = "Template python repository."
readme = "README.md"
keywords = [ "python" ]
license = { file = "LICENSE.txt" }
authors = [ { name = "Max" } ]
requires-python = ">=3.10"
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.12",
]
dependencies = [
  "numpy",
]

optional-dependencies.dev = [
  "black[jupyter]",
  "isort",
  "ruff",
  "template-python[test,docs]",
]
# https://medium.com/@pratikdomadiya123/build-project-documentation-quickly-with-the-sphinx-python-2a9732b66594
optional-dependencies.docs = [
  "ipykernel",
  "myst-parser",
  "nbconvert",
  "nbsphinx",
  "jupyterlab",
  "linkify-it-py",
  "pre-commit",
  "pyproject-fmt",
  "sphinx",
  "sphinx-book-theme",
  "sphinxcontrib-mermaid",
  "sphinx-design",
]
optional-dependencies.test = [ "coverage", "pytest" ]
urls."Source" = "https://github.com/max-models/template-python"
scripts.template-python = "app.main:main"

[tool.setuptools.packages.find]
where = [ "src" ]

[tool.isort]
profile = "black"
